### ISSUE TITLE
Trojan Horse Found!

### ISSUE THREAD

**Issue by Seal-Enthusiast** [PyPylia/ultrakill-save-editor#4]
Warning this program may contain a trojan horse 
after testing it in Virus total many sites showed that it has a Trojan.Malware.300983.susgen in it

Use at your own expense of security

**Comment by PyPylia** [comment]
Here is the VirusTotal scan of the latest release: https://www.virustotal.com/gui/file/20b99a9c4fd24d4389d7a5b8d687d27e6adb2891438aa713bd808dad8cf0d2dd

There is only one detection of "Trojan.Malware.300983.susgen" by MaxSecure. No large and reputable antivirus software detected anything. VirusTotal is prone to 1 or 2 false positives due to the amount of antivirus software it scans with.

If you still do not trust this software, feel free to read through the full source code, and recompile it yourself using rustc and cargo. It should produce an identical executable.
