### ISSUE TITLE
The app closes instantly after being launched

### ISSUE THREAD

**Issue by rom0119** [PyPylia/ultrakill-save-editor#6]
When i download the file,i open it and my pc security system ask me that am i sure that the file isn't a virus and when i allow opening it it closes instantly

**Comment by PyPylia** [comment]
The security warning is because the app is unsigned. A Windows executable signing certificate can cost a lot of money, which I can't afford. As such, Windows will always display a warning on the first launch as it can't verify its integrity. I can personally promise you, though, that it is safe, feel free to compile the program yourself from the source.

The issue with it instantly closing is due to a change in the save data format in the latest update. I am actively working on fixing this.

**Comment by rom0119** [comment]
Oh okay thanks sir!Just a little last question,do you know the exact date when you will release the fixed version?

**Comment by rom0119** [comment]
Hey uhh,PyPylia,is there any info about the issue and when is it gonna get fixed?
